# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [15]:
# Your code here
import numpy as np
A = np.array([[1,2,3],[1,2,3],[1,1,1]])
B = np.array([[4,5,6],[4,5,6],[1,1,1]])
C = np.array([[7,8,9],[7,8,9],[1,1,1]])
print(A*(B+C))
print((A*B)+(A*C))

[[11 26 45]
 [11 26 45]
 [ 2  2  2]]
[[11 26 45]
 [11 26 45]
 [ 2  2  2]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [16]:
# Your code here 
print(A.dot(B+C))
print(A.dot(B) + A.dot(C))

[[39 45 51]
 [39 45 51]
 [24 28 32]]
[[39 45 51]
 [39 45 51]
 [24 28 32]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [20]:
# Your code here 
print(A.dot(B))
print(B.dot(A))
x = A.dot(B) 
y = B.dot(A)
x==y

[[15 18 21]
 [15 18 21]
 [ 9 11 13]]
[[15 24 33]
 [15 24 33]
 [ 3  5  7]]


array([[ True, False, False],
       [ True, False, False],
       [False, False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [22]:
# Your code here 
x=np.array([[2],[3],[4]])
y=np.array([[5],[6],[7]])
np.transpose(x).dot(y)==np.transpose(y).dot(x)

array([[ True]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [23]:
# Your code here 
np.transpose(A.dot(B))== np.transpose(B).dot(np.transpose(A))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 